/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/lionheart-vpn/lionheart/mobile/golib */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "jni_bridge.go"

#include <jni.h>
#include <stdlib.h>
#include <android/log.h>

#define LOG_TAG "JNI_LIONHEART"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

static JavaVM* g_jvm = NULL;
static jobject g_service = NULL;
static jmethodID g_onStatusM = NULL;
static jmethodID g_onLogM = NULL;

static void cleanup_jni(JNIEnv* env) {
    if (g_jvm != NULL && g_service != NULL) {
        LOGI("Cleaning up JNI GlobalRef...");
        (*env)->DeleteGlobalRef(env, g_service);
        g_service = NULL;
    }
    g_onStatusM = NULL;
    g_onLogM = NULL;
}

static void init_jni(JNIEnv* env, jobject service) {
    LOGI("init_jni called");
    cleanup_jni(env);
    (*env)->GetJavaVM(env, &g_jvm);
    g_service = (*env)->NewGlobalRef(env, service);
    
    jclass cls = (*env)->GetObjectClass(env, service);
    if (!cls) {
        LOGE("Failed to get service class!");
        return;
    }
    
    g_onStatusM = (*env)->GetMethodID(env, cls, "onVpnStatusChanged", "(Ljava/lang/String;)V");
    g_onLogM = (*env)->GetMethodID(env, cls, "onNativeLog", "(Ljava/lang/String;Ljava/lang/String;)V");
    
    if (!g_onStatusM || !g_onLogM) {
        LOGE("Failed to find native callback methods! Check ProGuard rules.");
    } else {
        LOGI("JNI callbacks initialized successully");
    }
    
    (*env)->DeleteLocalRef(env, cls);
}

static void call_on_status(const char* status) {
    if (g_jvm == NULL || g_service == NULL || g_onStatusM == NULL) return;
    JNIEnv* env;
    jint res = (*g_jvm)->AttachCurrentThreadAsDaemon(g_jvm, (void**)&env, NULL);
    if (res != JNI_OK) return;
    jstring jStatus = (*env)->NewStringUTF(env, status);
    (*env)->CallVoidMethod(env, g_service, g_onStatusM, jStatus);
    (*env)->DeleteLocalRef(env, jStatus);
}

static void call_on_log(const char* level, const char* msg) {
    if (g_jvm == NULL || g_service == NULL || g_onLogM == NULL) return;
    JNIEnv* env;
    jint res = (*g_jvm)->AttachCurrentThreadAsDaemon(g_jvm, (void**)&env, NULL);
    if (res != JNI_OK) return;
    jstring jLevel = (*env)->NewStringUTF(env, level);
    jstring jMsg = (*env)->NewStringUTF(env, msg);
    (*env)->CallVoidMethod(env, g_service, g_onLogM, jLevel, jMsg);
    (*env)->DeleteLocalRef(env, jLevel);
    (*env)->DeleteLocalRef(env, jMsg);
}

static const char* env_GetStringUTFChars(JNIEnv* env, jstring str, jboolean* isCopy) {
    return (*env)->GetStringUTFChars(env, str, isCopy);
}

static void env_ReleaseStringUTFChars(JNIEnv* env, jstring str, const char* chars) {
    (*env)->ReleaseStringUTFChars(env, str, chars);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern jint Java_com_volfheim_bipbop_LionheartVpnService_startVpnNative(JNIEnv* env, jobject service, jstring smartKey, jint tunFd, jint mtu, jstring dns);
extern void Java_com_volfheim_bipbop_LionheartVpnService_reconnectVpnNative(JNIEnv* env, jobject service);
extern void Java_com_volfheim_bipbop_LionheartVpnService_stopVpnNative(JNIEnv* env, jobject service);

#ifdef __cplusplus
}
#endif
